name: pydexenv
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=3.2.3=py37he774522_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cloudpickle=1.3.0=py_0
  - colorama=0.4.1=py37_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37hfa6e2cd_0
  - dask-core=2.13.0=py_0
  - decorator=4.4.2=py_0
  - dicttoxml=1.7.4=py37_1
  - freetype=2.10.1=ha9979f8_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - imageio=2.8.0=py_0
  - importlib_metadata=1.1.0=py37_0
  - intel-openmp=2019.4=245
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.1.0=py37heaa310e_1
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.0.9=hf1753bf_1
  - matplotlib-base=3.2.1=py37h911224e_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - more-itertools=7.2.0=py37_0
  - networkx=2.4=py_1
  - nidaqmx-python=0.5.7=py_3
  - numpy=1.17.4=py37h4320e6b_0
  - numpy-base=1.17.4=py37hc3f5095_0
  - olefile=0.46=py_0
  - openssl=1.1.1e=hfa6e2cd_0
  - packaging=19.2=py_0
  - pillow=5.4.1=py37hdc69c19_0
  - pip=19.3.1=py37_0
  - pluggy=0.13.1=py37_0
  - psutil=5.6.7=py37he774522_0
  - py=1.8.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyqtgraph=0.10.0=py37h28b3542_3
  - pytest=5.3.1=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.6.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pywavelets=1.1.1=py37hc8d92b1_0
  - pywin32=223=py37hfa6e2cd_1
  - qt=5.9.7=vc14h73c81de_0
  - scikit-image=0.16.2=py37he350917_0
  - scipy=1.3.1=py37h29ff71c_0
  - setuptools=42.0.2=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tk=8.6.10=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37hfa6e2cd_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - xmltodict=0.12.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - colorlog==4.0.2
    - future==0.18.2
    - iso8601==0.1.13
    - pyserial==3.5
    - pyyaml==5.3.1
prefix: C:\Users\Lab\Anaconda3\envs\pydexenv
